### ISSUE TITLE
Vulnerable copy of libexpat in folder /development/core/src/SOCmn/expat?

### ISSUE THREAD

**Issue by hartwork** [SoftingIndustrial/OPC-Classic-SDK#1]
Hi!

From a quick look, the copy of libexpat at https://github.com/SoftingIndustrial/OPC-Classic-SDK/tree/main/development/core/src/SOCmn/expat is old and vulnerable — every release before 2.2.8 is. Are you aware?

Best, Sebastian

**Comment by FischerSeb** [comment]
Hi,
we are aware of this issue. This applies if you are using OPC-XML. This functionality in this product was discontinued from Softing long before those vulnerabilities were known. Therefore we did not fix this issues.
