### ISSUE TITLE
Demo Client help file missing

### ISSUE THREAD

**Issue by mkentie** [SoftingIndustrial/OPC-Classic-SDK#6]
The Demo Client .chm file isn't part of this distribution. It would be nice to have, we have built a 64-bit Demo Client for our internal usage, but it now lacks a help file.

**Comment by FischerSeb** [comment]
I am not sure which file you are referring. We have put all documentation on this repo. Under Programmer guide you find also the documentation for the client:
https://github.com/SoftingIndustrial/OPC-Classic-SDK/tree/main/documentation/3._Programmer%60s_Guide/6._Client

**Comment by mkentie** [comment]
Hi, I mean the SOClientE.chm / SOClientG.chm files teh Demo client tries to launch when you press F1.
![image](https://user-images.githubusercontent.com/11395695/149774669-722e0e3c-f321-4db4-bf80-6a09d1598bf6.png)

**Comment by FischerSeb** [comment]
I have added those files here:
https://github.com/SoftingIndustrial/OPC-Classic-SDK/tree/main/documentation/7._Demo_Client_Server_Doku
